[package]
name = "sophia_rio"
version = "0.7.0"
authors = ["Pierre-Antoine Champin <pchampin@liris.cnrs.fr>"]
edition = "2018"
description = "A Rust toolkit for RDF and Linked Data - Common code for Rio adapters"
repository = "https://github.com/pchampin/sophia_rs"
documentation = "https://docs.rs/sophia_rio"
readme = "../README.md"
license = "CECILL-B"
keywords = ["rdf", "linked-data", "semantic-web"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sophia_api = { version = "0.7.0", path = "../api" }
rio_api = { version = "0.6.0", features = ["generalized"] }

[dev-dependencies]
