[package]
name = "sophia_turtle"
version = "0.8.0-alpha"
authors = ["Pierre-Antoine Champin <pchampin@liris.cnrs.fr>"]
edition = "2021"
description = "A Rust toolkit for RDF and Linked Data - parsers and serializers for the Turtle-family of syntaxes"
repository = "https://github.com/pchampin/sophia_rs"
documentation = "https://docs.rs/sophia_turtle"
readme = "../README.md"
license = "CECILL-B"
keywords = ["rdf", "linked-data", "semantic-web"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = { version = "1.4.0" }
oxiri = "0.2.2"
regex = { version = "1.5.4" }
rio_turtle = { version = "0.8", features = ["generalized"] }
sophia_api = { version = "0.8.0-alpha", path = "../api" }
sophia_iri = { version = "0.8.0-alpha", path = "../iri" }
sophia_rio = { version = "0.8.0-alpha", path = "../rio" }

[dev-dependencies]
sophia_isomorphism = { version = "0.8.0-alpha", path = "../isomorphism" }

