[package]
name = "sophia"
version = "0.6.2"
authors = ["Pierre-Antoine Champin <pchampin@liris.cnrs.fr>"]
description = "A Rust toolkit for RDF and Linked Data"
repository = "https://github.com/pchampin/sophia_rs"
documentation = "https://docs.rs/sophia"
readme = "../README.md"
license = "CECILL-B"
keywords = ["rdf", "linked-data", "semantic-web"]
edition = "2018"

[package.metadata.docs.rs]
all-features = true

[features]
default = []
xml = ["lazy_static", "percent-encoding", "quick-xml", "sophia_iri", "regex", "rio_xml", "url"]

# This feature enables to use the graph and dataset test macros in other crates
test_macro = ["sophia_api/test_macro"]
# This feature enables a bunch of tests which, otherwise, make compilation really slow
all_tests = []

[dependencies]
sophia_api = { version = "0.6.2", path = "../api" }
sophia_term = { version = "0.6.2", path = "../term" }
resiter = "0.4.0"
rio_api = { version = "0.4.2", features = ["generalized"] }
rio_turtle = { version = "0.4.2", features = ["generalized"] }
thiserror = "1.0.20"

lazy_static = { version = "1.4.0", optional = true }
percent-encoding = { version = "2.1.0", optional = true }
quick-xml = { version = "0.18.1", optional = true }
regex = { version = "1.3.9", optional = true }
sophia_iri = { version = "0.6.2", path = "../iri", optional = true }
rio_xml = { version = "0.4.2", optional = true }
url = { version = "2.1.1", optional = true }

[dev-dependencies]
test-case = "1.0.0"
lazy_static = "1.4.0"
sophia_api = { version = "0.6.2", path = "../api", features = ["test_macro"] }

