[package]
name = "sophia"
version = "0.6.2"
authors = ["Pierre-Antoine Champin <pchampin@liris.cnrs.fr>"]
description = "A Rust toolkit for RDF and Linked Data"
repository = "https://github.com/pchampin/sophia_rs"
documentation = "https://docs.rs/sophia"
readme = "../README.md"
license = "CECILL-B"
keywords = ["rdf", "linked-data", "semantic-web"]
edition = "2018"

[package.metadata.docs.rs]
all-features = true

[features]
default = []
xml = ["percent-encoding", "quick-xml", "sophia_xml", "url"]

# This feature enables to use the graph and dataset test macros in other crates
test_macro = ["sophia_api/test_macro"]
# This feature enables a bunch of tests which, otherwise, make compilation really slow
all_tests = []

[dependencies]
lazy_static = { version = "1.4.0" }
regex = { version = "1.4.2" }
sophia_api = { version = "0.6.2", path = "../api" }
sophia_indexed = { version = "0.6.2", path = "../indexed" }
sophia_inmem = { version = "0.6.2", path = "../inmem" }
sophia_iri = { version = "0.6.2", path = "../iri" }
sophia_rio = { version = "0.6.2", path = "../rio" }
sophia_term = { version = "0.6.2", path = "../term" }
oxiri = "0.1.1"
resiter = "0.4.0"
rio_api = { version = "0.6.0", features = ["generalized"] }
rio_turtle = { version = "0.6.0", features = ["generalized"] }
thiserror = "1.0.20"

percent-encoding = { version = "2.1.0", optional = true }
quick-xml = { version = "0.22.0", optional = true }
sophia_xml = { version = "0.6.2", path = "../xml", optional = true }
url = { version = "2.2.0", optional = true }

[dev-dependencies]
test-case = "1.0.0"
lazy_static = "1.4.0"
sophia_api = { version = "0.6.2", path = "../api", features = ["test_macro"] }
criterion = "0.3.3"

[[bench]]
name = "main"
harness = false
