[package]
name = "sophia"
version = "0.8.0-alpha"
authors = ["Pierre-Antoine Champin <pchampin@liris.cnrs.fr>"]
edition = "2021"
description = "A Rust toolkit for RDF and Linked Data"
repository = "https://github.com/pchampin/sophia_rs"
documentation = "https://docs.rs/sophia"
readme = "../README.md"
license = "CECILL-B"
keywords = ["rdf", "linked-data", "semantic-web"]

[package.metadata.docs.rs]
all-features = true

[features]
default = []
# This feature enables the RDF/XML parser and serializer
xml = ["sophia_xml"]
# This feature enables to use the graph and dataset test macros in other crates
test_macro = ["sophia_api/test_macro"]

[dependencies]
sophia_iri = { version = "0.8.0-alpha", path = "../iri" }
sophia_api = { version = "0.8.0-alpha", path = "../api" }
sophia_inmem = { version = "0.8.0-alpha", path = "../inmem" }
sophia_isomorphism = { version = "0.8.0-alpha", path = "../isomorphism" }
sophia_rio = { version = "0.8.0-alpha", path = "../rio" }
sophia_turtle = { version = "0.8.0-alpha", path = "../turtle" }
sophia_xml = { version = "0.8.0-alpha", path = "../xml", optional = true }
