[package]
name = "sophia_jsonld"
version = "0.7.2"
authors = ["Pierre-Antoine Champin <pchampin@liris.cnrs.fr>"]
edition = "2021"
description = "A Rust toolkit for RDF and Linked Data - JSON-LD serializer"
repository = "https://github.com/pchampin/sophia_rs"
documentation = "https://docs.rs/sophia_jsonld"
readme = "../README.md"
license = "CECILL-B"
keywords = ["rdf", "linked-data", "semantic-web", "json-ld"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.19", optional = true }
json = "0.12.4"
sophia_api = { version = "0.7.2", path = "../api" }
sophia_iri = { version = "0.7.2", path = "../iri" }
sophia_term = { version = "0.7.2", path = "../term" }
sophia_turtle = { version = "0.7.2", path = "../turtle" }
thiserror = "1.0.30"

[[bin]]
name = "report"
required-features = ["test_util"]
test = false

[features]
default = []
test_util = ["chrono"]